export enum DrawMarkerEvents {
  DRAW_MARKER_DISABLED = 'DRAW_MARKER_DISABLED',
  DRAW_MARKER_EDITED = 'DRAW_MARKER_EDITED',
  DRAW_MARKER_ENABLED = 'DRAW_MARKER_ENABLED',
  DRAW_MARKER_END = 'MARKER_DRAW_END',
  DRAW_MARKER_SAVE = 'MARKER_DRAW_SAVE',
  DRAW_MARKER_START = 'MARKER_DRAW_START',
  DRAW_MARKER_PLACED = 'MARKER_PLACED',
}
