export enum DrawPolygonEvents {
  DRAW_POLYGON_DISABLED = 'DRAW_POLYGON_DISABLED',
  DRAW_POLYGON_EDITED = 'DRAW_POLYGON_EDITED',
  DRAW_POLYGON_ENABLED = 'DRAW_POLYGON_ENABLED',
  DRAW_POLYGON_END = 'POLYGON_DRAW_END',
  DRAW_POLYGON_SAVE = 'POLYGON_DRAW_SAVE',
  DRAW_POLYGON_START = 'POLYGON_DRAW_START',
}
