export enum DrawPolylineEvents {
  DRAW_POLYLINE_DISABLED = 'DRAW_POLYLINE_DISABLED',
  DRAW_POLYLINE_EDITED = 'DRAW_POLYLINE_EDITED',
  DRAW_POLYLINE_ENABLED = 'DRAW_POLYLINE_ENABLED',
  DRAW_POLYLINE_END = 'POLYLINE_DRAW_END',
  DRAW_POLYLINE_SAVE = 'POLYLINE_DRAW_SAVE',
  DRAW_POLYLINE_START = 'POLYLINE_DRAW_START',
}
